### PR TITLE
Jetty93 Fixes for #61 and #62

### LINKED ISSUE #61: Pure Jetty 9 image should mimic official docker-jetty entry point and documentation
The pure jetty 9 image should have the same entry point as the docker-jetty official image.
The similarities and customization should be documented in a README.md

### PR DESCRIPTION
**Pull request by gregw**
Updated Jetty93 Branch to fix #61 and #62 

The gce images now contain README.md files with some minimal documentation.

All the images now follow the docker best practise of having an entry point that can accept either other commands (eg bash) or arguments (eg --module=foobar) for the default entry point.

Removed the general deployer from the GAE image and replaced with a single webapp deployer.

### CODE REVIEW

File: appengine-jetty-managed-runtime/src/main/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeWebAppDeployer.java [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+import org.eclipse.jetty.server.handler.ContextHandlerCollection;
+import org.eclipse.jetty.util.annotation.Name;
+import org.eclipse.jetty.util.component.AbstractLifeCycle;
+import org.eclipse.jetty.util.resource.Resource;
+import org.eclipse.jetty.webapp.WebAppContext;
+import org.eclipse.jetty.xml.XmlConfiguration;
+
+public class VmRuntimeWebAppDeployer extends AbstractLifeCycle
+{
+  private final ContextHandlerCollection contexts;
```
Comment (ludoch) [inline appengine-jetty-managed-runtime/src/main/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeWebAppDeployer.java]: Will reformat later, but our conventions are { at the end of the code line, and {} even for 1 line if/else statements.

Comment (gregw) [inline appengine-jetty-managed-runtime/src/main/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeWebAppDeployer.java]: Trying very hard to comply with that.... have created and eclipse IDE that I think complies with your coding standards... but my subconscious obviously is still rebelling against unbalanced curlies and sneaks a few in still :)
